WebApplication1/Controllers/ActivityController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheOneTag.Services;

namespace WebApplication1.Controllers
{
    public class ActivityController : Controller
    {
        // GET: Activity
        public ActionResult Index()
        {
            var service = CreateActivityService();
            var model = service.GetAllApplicationUsers();
            return View(model);
        }

        public ActionResult GetLeaguesForPlayer(int id)
        {
            var service = CreateActivityService();
            var model = service.GetAllLeaguesForPlayer(id);

            if (model is null)
            {
                return RedirectToAction("Index");
                //TempData
            }

            if (model != null)
            {
                var league = model.FirstOrDefault();
                if (league != null)
                {
                    var player = league.PlayerName;
                    ViewBag.User = $"{player}'s Leagues";
                    return View(model);
                }
            }

            ModelState.AddModelError("", "Player has not played any League Rounds");

            return RedirectToAction("Index");

        }

        private ActivityService CreateActivityService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());

            if (userId != null)
            {
                var service = new ActivityService(userId);
                return service;
            }

            var serviceNoLogin = new ActivityService();
            return serviceNoLogin;
        }


    }
}

WebApplication1/Controllers/LeagueController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheOneTag.Models;
using TheOneTag.Services;

namespace WebApplication1.Controllers
{
    
    public class LeagueController : Controller
    {
        // GET: League
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new LeagueService(userId);
            var model = service.GetLeagues();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize, HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(LeagueCreate model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var service = CreateLeagueService();

            if (service.CreateLeague(model))
            {
                TempData["SaveResult"] = "Your league was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "League could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var service = CreateLeagueService();
            var model = service.GetLeagueById(id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateLeagueService();
            var detail = service.GetLeagueById(id);
            var model =
                new LeagueEdit
                {
                    LeagueId = detail.LeagueId,
                    LeagueName = detail.LeagueName,
                    LeagueZipCode = detail.ZipCode
                };
            return View(model);
        }


        [HttpPost, ValidateAntiForgeryToken, Authorize]
        public ActionResult Edit(int id, LeagueEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.LeagueId != id)
            {
                ModelState.AddModelError("", "ID mismatch");
                return View(model);
            }
            var service = CreateLeagueService();
            if (service.UpdateLeague(model))
            {
                TempData["SaveResult"] = "Your league was updated";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your league could not be udpated.");
            return View();
        }

        [HttpGet, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var service = CreateLeagueService();
            var model = service.GetLeagueById(id);

            return View(model);
        }

        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public ActionResult LeagueDelete(int id)
        {
            var service = CreateLeagueService();
            service.DeleteLeague(id);
            TempData["SaveResult"] = "Your league was deleted";
            return RedirectToAction("Index");
        }

        public ActionResult DeletePlayerFromLeague(string id, int leagueId)
        {
            var service = CreateLeagueService();
            var detail = service.GetPlayerById1(id, leagueId);
           
            return View(detail);
        }

        [Authorize]
        [HttpPost]
        [ActionName("DeletePlayerFromLeague")]
        public ActionResult DeletePlayerFromLeagues(string id, int leagueId)
        {
            if (!ModelState.IsValid)
                return HttpNotFound();

            var service = CreateLeagueService();
            service.DeletePlayerFromLeague(id, leagueId);
            TempData["SaveResult"] = "Player was deleted";
            
            return RedirectToAction($"PlayLeagueRound/{leagueId}");

        }

        [ActionName("AddPlayer"), Authorize]
        public ActionResult AddPlayerToLeague(int id)
        {
            var service = CreateLeagueService();

            if (!service.AddPlayerToLeague(id))
            {
                TempData["NotSaved"] = "Player is already in league.";
                return RedirectToAction("Index");
            }

            TempData["SaveResult"] = "Player was added to league.";
            return RedirectToAction("Index");
        }
        
        public ActionResult PlayLeagueRound(int id)
        {
            //User needs to checkmark all players who are playing the round, return PlayRound Model with all info added for each player playing.
            var service = CreateLeagueService();
            var model = service.GetPlayerListByLeagueId(id);
            ViewBag.leagueId = id;
            return View(model);
            
        }


        [Authorize]
        public ActionResult PlayRound(int id)
        {
            //This should take the PlayRound model and use the information to reorder the players and edit the players ranking in the UserLeague junction table entity.
            var service = CreateLeagueService();

            if (!service.PlayLeagueRound(id))
                ModelState.AddModelError("", "Your ranks have not been updated.");

            ViewBag.id = id;
            
            //I want to return a view of the League with the Players in their new ranking.
            return RedirectToAction($"PlayLeagueRound/{id}");
        }

        
        public ActionResult UserLeagueEdit(string id, int leagueId)
        {
            var service = CreateLeagueService();
            var detail = service.GetPlayerById(id);
            var model =
                new UserLeagueEdit
                {
                    Score = detail.Score,
                    ID = detail.Id,
                    LeagueId = leagueId,
                    PlayerName = detail.FirstName + " " + detail.LastName
                };
            return View(model);
        }

        //Create UserLeagueEdit View
        [HttpPost, ValidateAntiForgeryToken, Authorize]
        public ActionResult UserLeagueEdit(UserLeagueEdit model)
        {
            var service = CreateLeagueService();

            
            service.UpdateUserLeagueScore(model);
            return RedirectToAction($"PlayLeagueRound/{model.LeagueId}");
        }

        private LeagueService CreateLeagueService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new LeagueService(userId);
            return service;
        }

        // Service to re-order tags if records have been deleted from the database.
        public ActionResult ResetRanks(int leagueId)
        {
            var service = CreateLeagueService();

            if (service.ResetScores(leagueId) == true)
            return RedirectToAction($"PlayLeagueRound/{leagueId}");

            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

WebApplication1/Views/Activity/GetLeaguesForPlayer.cshtml
@model IEnumerable<TheOneTag.Models.ActivityPlayerLeagueListItem>

@{
    ViewBag.Title = "GetLeaguesForPlayer";
}
<br />
<br />

<h2>@Html.ViewBag.User </h2>

<br />
<br />

<div class="player-league-board">
    @foreach (var item in Model)
    {
        <div class="card-container col-md-3 col-sm-6">
            <div class="league-card">
                <div class="league-head">
                    @Html.DisplayFor(modelItem => item.LeagueName)
                </div>
                <div class="league-body">
                    <div class="league-detail">
                        League Ranking:
                        @Html.DisplayFor(modelItem => item.LeagueRanking)
                        <br />
                        Average Ranking:
                        @Html.DisplayFor(modelItem => item.AverageRanking)
                        <br />
                        Biggest Rank Jump:
                        @Html.DisplayFor(modelItem => item.BiggestRankingJump)
                        <br />
                        League Rounds This Person Has Played:
                        @Html.DisplayFor(modelItem => item.LeagueRoundsPlayed)
                        <br />
                        @Html.ActionLink("Details", "Details", "League", new { id = item.LeagueId }, new { @style = "", @class = "link-text" })
                    </div>

                </div>
            </div>
        </div>
    }
</div>
<br />

WebApplication1/Views/Activity/Index.cshtml
@model IEnumerable<TheOneTag.Models.ActivityPlayerListItem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    
</p>
<table class="table">
    <tr>
        <th>

        </th>
        <th>
            
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PdgaNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.HiddenFor(modelItem => item.PlayerId)
    </td>
    <td>
        @Html.HiddenFor(modelItem => item.IdHash)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PdgaNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LastName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FullName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ZipCode)
    </td>
    <td>

        @Html.ActionLink("Details", "GetLeaguesForPlayer", new { id = item.IdHash })

    </td>
</tr>
}

</table>